### PR TITLE
Added possiblity to configure interval updated topics

### PR DESCRIPTION
**Pull request by sweber**
In conjuction with evcc (https://evcc.io) an constant update of certain topics is needed to ensure the state doesn't get stale.

This change adds a mechanism to configure the update topics aswell as a update interval.

### CODE REVIEW

**Comment by jagheterfredrik** [comment]
Not sure I get it. What is missing for evcc to work?

**Comment by sweber** [comment]
The wallbox sends the enabled state only when it changes. Which it's perfectly fine in normal circumstances.  However evcc has an internal timer after which it assumes that the wallbox is kind of offline if there is no new enabled message.
With my change the enable state and charging power gets send periodically to ensure evcc works fine.

Regards Stefan

P.S. i understand if you do not want the change in your code base. I did it in my repository  and me neighbour and i are running the changed build with great success

**Comment by jagheterfredrik** [comment]
I see and happy that it works but I think the fix should do into evcc. As a stop gap perhaps set timeout to something really big (https://docs.evcc.io/docs/reference/plugins#mqtt-lesenschreiben)?

**Comment by jagheterfredrik** [comment]
Specifically the bridge offers an availability topic for this purpose using mqtt last will and testament

**Comment by sweber** [comment]
Sadly the LWT will not solve the issue.
However we are very pleased with you bridge and are using it with great success.
I fully understand your decision to not merge my changes. Feel free to close and discard this PR.

Thanks

**Comment by sincze** [comment]
Hi.

I noticed this nice however closed PR and as I can agree on the time-out setting being an EVCC challenge  (I have the same time-out for my solar panels at night ;-)) , there still seems to be something missing in this great piece of bridge software.

This PR initiative in my opinion is the ideal candidate for 100% EVCCcompatibility based on the following.

EVCC needs some states like A,B,C... as mentioned in the generic Wallbox setup.
```
chargers:
  - name: my_charger
    type: custom
    status: # charger status A..F
      source: ...
      # ...
    enabled: # charger enabled state (true/false or 0/1)
      source: ...
      # ...
    enable: # set charger enabled state (true/false or 0/1)
      source: ...
      # ...
    maxcurrent: # set charger max current (A)
      source: ...
      # ...
```

So what does this status: # charger status A..F mean?? I found the following:

```
Zustand | Fzg. angeschlossen | Laden möglich | Spannung CP-PE | Frequenz
------- | ------------------ | ------------- | -------------- | ----------
A       | Nein               | Nein          | 12V            |  DC
B       | Ja                 | Nein          | 9V/-12V        | 1 kHz
C       | Ja                 | Ja            | 6V/-12V        | 1 kHz
D       | Ja                 | Ja            | 3V/-12V        | 1 kHz
E       | Ja                 | Nein          | 0V             | -
F       | Ja                 | Nein          | -              | -
```

That piece of data is currently available in the bridge somewhere however not pushed to MQTT as such..
[link](https://github.com/jagheterfredrik/wallbox-mqtt-bridge/blob/main/app/wallbox/wallbox_const.go
)

I found this:
https://github.com/sweber/wallbox-mqtt-bridge/releases/tag/v20241029_1

where the necessary data for EVCC is published correctly.

```
control_pilot: (A,B,C,E,F)
control_pilot_detail: (A1, A2, B1, B2, C1, C2, E, F)
control_pilot_detail_message: (Ready 1, Ready 2, ...)
```

To integrate a wallbox in EVCC you normally would have to go the OCPP way,.
https://docs.evcc.io/en/docs/devices/chargers#pulsar-plus-pulsar-max-commander-2-copper-sb-fw-5x


Are you open for this (status) enhancement as a PR? 
I do not see any issues if we disregard the timeout thing, only enhancements to have people using this bridge with more integration possibilities..

**Comment by jagheterfredrik** [comment]
I believe all relevant status sensors are available when turning on debug sensors. Again I think it makes sense for evcc to integrate with the bridge, not the other way around.

I haven’t used evcc but it seems chargers are plugins, here is one that uses mqtt: https://github.com/evcc-io/evcc/blob/master/charger/warp2.go

**Comment by sweber** [comment]
> I believe all relevant status sensors are available when turning on debug sensors. Again I think it makes sense for evcc to integrate with the bridge, not the other way around.
> 
> I haven’t used evcc but it seems chargers are plugins, here is one that uses mqtt: https://github.com/evcc-io/evcc/blob/master/charger/warp2.go

Yes you can get it to work with the generic mqtt charger. However it is not a good solution since you rely on data that might not represent the correct states.

The control pilot values are clearly defined by the DIN EN 61851-1:201 they are `A,B, C, D, E, F`. Even the Pulsar Plus CP states are miss leading since there is a differentiation in A1,A2;B1,B2 and C1,C2. Those are not as specified. I just cleared it up so that downstream projects can use the 'correct' CP states.

However it is still you project and you and only you decided if you want to integrate changes or not.

**Comment by jagheterfredrik** [comment]
I'm saying to make it work in EVCC using a custom plugin that takes the LWT in to account.

The control states are defined differently in the Wallbox by Wallbox and my aim is to reduce the amount of transformations needed inside the Wallbox as I want a stable interface and I think transformations are better handled in integration X, Y, Z as they see fit.
I'm not opposed to promoting these sensors from being "debug sensors".

**Pull request closed without merging**
