### PR TITLE
Fix added energy and range, add back charging power

### PR DESCRIPTION
**Pull request by tronikos**
- Fix added energy and range by getting the values from the active session if available otherwise from the latest session
- Add back the charging power getting the value from the state_values table instead of the stale charging_power field in active_session that doesn't get updated when paused or finished charging.

### CODE REVIEW

**Comment by jagheterfredrik** [comment]
Not sure about the `IF(`active_session`.`id` != 1,`, mine is now showing the last session even though the car is plugged in.

**Comment by jagheterfredrik** [comment]
For power, the state_values only update every 30 minutes, the power is available in redis at `HGET m2w tms.line1.power_watt.value`

**Comment by tronikos** [comment]
Sorry I meant to check user_id not id. user_id is 1 if not active, non 1 if active.
For me state_values updates every 10 seconds.

**Comment by tronikos** [comment]
Given that the a user reported was_connected isn't working, should we switch to checking the user_id instead of was_connected that you do in https://github.com/jagheterfredrik/wallbox-mqtt-bridge/pull/4 ?

**Comment by tronikos** [comment]
I asked the user at https://community.home-assistant.io/t/wallbox-pulsar-plus-integration/200339/866

**Comment by jagheterfredrik** [comment]
I think that makes sense. Thanks for checking with him

**Pull request merged**
