### PR TITLE
Add state overrides

### PR DESCRIPTION
**Pull request by tronikos**
Port https://github.com/jagheterfredrik/wallbox-mqtt-bridge-go/pull/4

### CODE REVIEW

**Comment by jagheterfredrik** [comment]
There is a Charger status ”Queue by power boost”, does that not happen?

**Comment by tronikos** [comment]
No, the charger status was Paused.
Looks like we need to switch to the session.state which seems more reliable and is what the app seems to display.

**Comment by jagheterfredrik** [comment]
I need to investigate as I thought the app only got charger status, lock state and charge enable

**Comment by jagheterfredrik** [comment]
I’ve been meaning to look into it as the above doesn’t explain how it gets the “waiting unlock” as “locked”

**Comment by tronikos** [comment]
Do you want to merge this in the meantime?

**Comment by jagheterfredrik** [comment]
I’ve found a couple of more overrides but feel free to merge if you don’t want to wait

**Comment by tronikos** [comment]
No worries I can wait

**Comment by jagheterfredrik** [comment]
Here are the states as seen from Bluetooth

```
switch (state_machine_state) {
  case 0xa1:
    // "READY"
    status = 0;
    break;
  case 0xa2:
    // "PS_UNCONFIG: unconfigured Power Sharing"
    status = 9;
    break;
  case 0xa3:
    // "UNAVAILABLE"
    status = 0xe;
    break;
  case 0xa4:
    // "FINISHED"
    status = 0xf;
    break;
  default:
    // "ERROR"
    status = 7;
    break;
  case 0xa6:
    // "UPDATING: installing updates"
    status = 0x11;
    break;
  case 0xb1:
  case 0xb3:
    // "CONNECTED: waiting for next schedule"
    status = 3;
    break;
  case 0xb2:
  case 0xb6:
    // "CONNECTED: paused by user"
    status = 4;
    break;
  case 0xb4:
  case 0xb5:
    // "CONNECTED: waiting for car demand"
    status = 2;
    break;
  case 0xb7:
  case 0xb8:
    // "CONNECTED: waiting for Power Sharing current assignation"
    status = 8;
    break;
  case 0xb9:
  case 0xba:
    // "CONNECTED: waiting for Home Sharing current assignation"
    status = 10;
    break;
  case 0xbb:
    // "CONNECTED: MID failed before start"
    status = 0xc;
    break;
  case 0xbc:
    // "CONNECTED: MID failed during charge"
    status = 0xd;
    break;
  case 0xbd:
    // "WAIT_ECO_POWER: in queue by EcoSmart"
    status = 0x12;
    break;
  case 0xc1:
  case 0xc2:
    // "CHARGING"
    status = 1;
    break;
  case 0xc3:
  case 0xc4:
    // "DISCHARGING"
    status = 0xb;
    break;
  case 0xd1:
  case 0xd2:
    // "LOCK: locked (not charging | waiting to unlock)"
    status = 6;
    break;
}
```

**Comment by jagheterfredrik** [comment]
https://github.com/jagheterfredrik/wallbox-mqtt-bridge-go/pull/4/files

**Comment by tronikos** [comment]
Thanks. I ported your changes in https://github.com/jagheterfredrik/wallbox-mqtt-bridge-go/pull/4
By the way, what are your plans with the Python version? Deprecate and archive this repo and encourage everyone to switch to the Go version?

**Comment by jagheterfredrik** [comment]
What’s your opinion? I like the fact that it can use the latest dependencies, is fully self contained and typed 🙊

**Comment by tronikos** [comment]
+1 on switching to the Go version. On my Wallbox it seems to consume less resources than the Python version.

**Pull request merged**
